CREATE TABLE users (user_id int(10) NOT NULL AUTO_INCREMENT, username varchar(20) NOT NULL UNIQUE, password varchar(20) NOT NULL, email varchar(50) NOT NULL UNIQUE, name varchar(255) NOT NULL, employee_number int(10), departments_dep_id int(11) NOT NULL, payment_type bit(1) DEFAULT 0 NOT NULL, discount int(2), user_status bit(1), logins int(10) DEFAULT 0 NOT NULL, last_login int(10) DEFAULT Null, PRIMARY KEY (user_id));
CREATE TABLE orders (order_id int(10) NOT NULL AUTO_INCREMENT, user_id int(10) NOT NULL, delivery_times_delivery_id int(10), order_date date NOT NULL, delivery_date date NOT NULL, delivery_point varchar(10) NOT NULL, order_status varchar(20) DEFAULT 'Not Staffed' NOT NULL, total_price numeric(5, 2), subscription_subs_id int(10), PRIMARY KEY (order_id));
CREATE TABLE orders_records (order_id int(10) NOT NULL, menu_record_menu_id int(5) NOT NULL, menu_record_dish_id int(10) NOT NULL, servings_number int(3) NOT NULL, PRIMARY KEY (order_id, menu_record_menu_id, menu_record_dish_id));
CREATE TABLE menus (menu_id int(5) NOT NULL AUTO_INCREMENT, menu_date date NOT NULL UNIQUE, type varchar(10) NOT NULL, PRIMARY KEY (menu_id));
CREATE TABLE menu_records (menu_id int(5) NOT NULL, dish_id int(10) NOT NULL, price double NOT NULL, PRIMARY KEY (menu_id, dish_id));
CREATE TABLE dishes (dish_id int(10) NOT NULL AUTO_INCREMENT, dish_name varchar(20) NOT NULL, type varchar(10) NOT NULL, is_standart bit(1) NOT NULL, PRIMARY KEY (dish_id));
CREATE TABLE ingredients (dish_id int(10) NOT NULL, product_id int(10) NOT NULL, yield double NOT NULL, PRIMARY KEY (dish_id, product_id));
CREATE TABLE products (product_id int(10) NOT NULL AUTO_INCREMENT, product_name varchar(20) NOT NULL, balance double NOT NULL, PRIMARY KEY (product_id));
CREATE TABLE subscriptions (subs_id int(10) NOT NULL AUTO_INCREMENT, user_id int(10) NOT NULL, start_date date NOT NULL, end_date date, status varchar(10), PRIMARY KEY (subs_id));
CREATE TABLE roles (role_id int(10) NOT NULL AUTO_INCREMENT, role_name varchar(20) NOT NULL UNIQUE, PRIMARY KEY (role_id));
CREATE TABLE roles_users (role_id int(10) NOT NULL, user_id int(10) NOT NULL);
CREATE TABLE menu_buttons (id int(11) NOT NULL AUTO_INCREMENT, name varchar(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE roles_buttons (roles_role_id int(10) NOT NULL, menu_buttons_id int(11) NOT NULL, PRIMARY KEY (roles_role_id, menu_buttons_id));
CREATE TABLE delivery_times (delivery_id int(10) NOT NULL AUTO_INCREMENT, delivery_time time NOT NULL, delivery_limit int(11) NOT NULL, PRIMARY KEY (delivery_id));
CREATE TABLE departments (dep_id int(11) NOT NULL AUTO_INCREMENT, name varchar(20) NOT NULL, building varchar(20) NOT NULL, office varchar(11) NOT NULL, floor varchar(11), PRIMARY KEY (dep_id));
ALTER TABLE orders_records ADD INDEX FKorders_rec398980 (order_id), ADD CONSTRAINT FKorders_rec398980 FOREIGN KEY (order_id) REFERENCES orders (order_id);
ALTER TABLE orders ADD INDEX FKorders458716 (user_id), ADD CONSTRAINT FKorders458716 FOREIGN KEY (user_id) REFERENCES users (user_id);
ALTER TABLE menu_records ADD INDEX FKmenu_recor596691 (menu_id), ADD CONSTRAINT FKmenu_recor596691 FOREIGN KEY (menu_id) REFERENCES menus (menu_id);
ALTER TABLE orders_records ADD INDEX FKorders_rec170609 (menu_record_menu_id, menu_record_dish_id), ADD CONSTRAINT FKorders_rec170609 FOREIGN KEY (menu_record_menu_id, menu_record_dish_id) REFERENCES menu_records (menu_id, dish_id);
ALTER TABLE menu_records ADD INDEX FKmenu_recor558008 (dish_id), ADD CONSTRAINT FKmenu_recor558008 FOREIGN KEY (dish_id) REFERENCES dishes (dish_id);
ALTER TABLE ingredients ADD INDEX FKingredient247026 (dish_id), ADD CONSTRAINT FKingredient247026 FOREIGN KEY (dish_id) REFERENCES dishes (dish_id);
ALTER TABLE ingredients ADD INDEX FKingredient535850 (product_id), ADD CONSTRAINT FKingredient535850 FOREIGN KEY (product_id) REFERENCES products (product_id);
ALTER TABLE orders ADD INDEX FKorders354629 (subscription_subs_id), ADD CONSTRAINT FKorders354629 FOREIGN KEY (subscription_subs_id) REFERENCES subscriptions (subs_id);
ALTER TABLE roles_users ADD INDEX FKroles_user5600 (role_id), ADD CONSTRAINT FKroles_user5600 FOREIGN KEY (role_id) REFERENCES roles (role_id);
ALTER TABLE roles_users ADD INDEX FKroles_user812322 (user_id), ADD CONSTRAINT FKroles_user812322 FOREIGN KEY (user_id) REFERENCES users (user_id);
ALTER TABLE roles_buttons ADD INDEX FKroles_butt646858 (roles_role_id), ADD CONSTRAINT FKroles_butt646858 FOREIGN KEY (roles_role_id) REFERENCES roles (role_id);
ALTER TABLE roles_buttons ADD INDEX FKroles_butt17717 (menu_buttons_id), ADD CONSTRAINT FKroles_butt17717 FOREIGN KEY (menu_buttons_id) REFERENCES menu_buttons (id);
ALTER TABLE orders ADD INDEX FKorders486885 (delivery_times_delivery_id), ADD CONSTRAINT FKorders486885 FOREIGN KEY (delivery_times_delivery_id) REFERENCES delivery_times (delivery_id);
ALTER TABLE users ADD INDEX FKusers754823 (departments_dep_id), ADD CONSTRAINT FKusers754823 FOREIGN KEY (departments_dep_id) REFERENCES departments (dep_id);
ALTER TABLE subscriptions ADD INDEX FKsubscripti680232 (user_id), ADD CONSTRAINT FKsubscripti680232 FOREIGN KEY (user_id) REFERENCES users (user_id);
