INSERT INTO `dish_category` VALUES (1, 'Супы', 1);
INSERT INTO `dish_category` VALUES (2, 'Закуски', 2);
INSERT INTO `dish_category` VALUES (3, 'Горячее', 3);
INSERT INTO `dish_category` VALUES (4, 'Напитки безалкогольн', 4);
INSERT INTO `dish_category` VALUES (5, 'Вина', 5);
INSERT INTO `dish_category` VALUES (6, 'Пиво', 6);
INSERT INTO `dish_category` VALUES (12, 'Шампанское', 10);
INSERT INTO `dish_category` VALUES (13, 'Белые вина', 10);
INSERT INTO `dish_category` VALUES (14, 'Розовые вина', 10);
INSERT INTO `dish_category` VALUES (15, 'Красные вина', 10);
INSERT INTO `dish_category` VALUES (16, 'Ликеры', 10);
INSERT INTO `dish_category` VALUES (17, 'Коньяк', 10);
INSERT INTO `dish_category` VALUES (18, 'Кальвадос', 10);
INSERT INTO `dish_category` VALUES (19, 'Бренди', 10);
INSERT INTO `dish_category` VALUES (20, 'Виски', 10);
INSERT INTO `dish_category` VALUES (21, 'Ром', 10);
INSERT INTO `dish_category` VALUES (22, 'Джин', 10);
INSERT INTO `dish_category` VALUES (23, 'Текила', 10);
INSERT INTO `dish_category` VALUES (24, 'Водка', 10);
